"""update models

Revision ID: 008740b73622
Revises: 09c80d961370
Create Date: 2025-09-24 18:41:44.331189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008740b73622'
down_revision = '09c80d961370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatroom_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatroom_types', schema=None) as batch_op:
        batch_op.drop_column('config')

    # ### end Alembic commands ###
