"""FIxing items

Revision ID: 18b35849e998
Revises: 
Create Date: 2025-09-17 19:16:32.114517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b35849e998'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chatroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chatroom', schema=None) as batch_op:
        batch_op.drop_column('trash')

    # ### end Alembic commands ###
