"""column to bugreport and suggestion

Revision ID: 35583658cbdc
Revises: b8bca536ce09
Create Date: 2025-09-25 22:49:21.984373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35583658cbdc'
down_revision = 'b8bca536ce09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('bug_reports', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
