"""fixing further

Revision ID: 555293d2d1c7
Revises: 18b35849e998
Create Date: 2025-09-17 19:24:26.044527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555293d2d1c7'
down_revision = '18b35849e998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('answers_questionId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'questions', ['questionId'], ['questionId'], ondelete='CASCADE')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('messages_chatRoomId_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_accountId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chatrooms', ['chatRoomId'], ['chatRoomId'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'accounts', ['accountId'], ['accountId'], ondelete='CASCADE')

    with op.batch_alter_table('user_chatroom', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_chatroom_accountId_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_chatroom_chatRoomId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['accountId'], ['accountId'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'chatrooms', ['chatRoomId'], ['chatRoomId'], ondelete='CASCADE')
        batch_op.drop_column('trash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_chatroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_chatroom_chatRoomId_fkey'), 'chatrooms', ['chatRoomId'], ['chatRoomId'])
        batch_op.create_foreign_key(batch_op.f('user_chatroom_accountId_fkey'), 'accounts', ['accountId'], ['accountId'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_accountId_fkey'), 'accounts', ['accountId'], ['accountId'])
        batch_op.create_foreign_key(batch_op.f('messages_chatRoomId_fkey'), 'chatrooms', ['chatRoomId'], ['chatRoomId'])

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('answers_questionId_fkey'), 'questions', ['questionId'], ['questionId'])

    # ### end Alembic commands ###
