"""change profileimage to avatar

Revision ID: 9ba7c712fbc8
Revises: 008740b73622
Create Date: 2025-09-24 22:25:36.878962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba7c712fbc8'
down_revision = '008740b73622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=500), nullable=True))
        batch_op.drop_column('profileImage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profileImage', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
