"""Bugerports and suggestions

Revision ID: b8bca536ce09
Revises: 9ba7c712fbc8
Create Date: 2025-09-25 22:46:53.010135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bca536ce09'
down_revision = '9ba7c712fbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('reportId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('reportId')
    )
    op.create_table('suggestions',
    sa.Column('suggestionId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('suggestionId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestions')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###
