name: Build frontend

on:
  workflow_dispatch: # manual trigger

env:
  FRONTEND_IMAGE: jetpans/xqzite:frontend-latest
jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

   
    - name: Build frontend Docker image
      run: |
        docker build -f ./Dockerfile -t xqz-frontend .
        docker tag xqz-frontend $FRONTEND_IMAGE


    - name: Push frontend image to Docker Hub
      run: docker push $FRONTEND_IMAGE
